jnosql:
  tinkerpop:
    host: ws://localhost:8182
    user: neo4j
    password: admin123
  graph:
    provider: org.eclipse.jnosql.mapping.graph.connections.TinkerpopGraphConfiguration

traversals:
  filename: traversals.yml
spring:
  application:
    name: pocs
  datasource:
    driver-class-name: org.postgresql.Driver
    username: usrdev
    password: P@ssw0rd
    platform: postgres
    url: jdbc:postgresql://localhost:5432/pocs_db
    initialization-mode: always
    continue-on-error: true
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        ddl-auto: update
      generate-ddl: true
server:
  port: 4000
  servlet:
    context-path: /pocs
aws:
  ssm:
    region: ca-central-1
  neptune:
    host: neptunedbinstance-zvdnrtvv7jvh.c9popfp3zboh.ca-central-1.neptune.amazonaws.com
    port: 8182
    username:
    password:
    enableSsl: false
    keystore:
    keystorePassword:
    maxConnectionPoolSize: 2
    maxInProcessPerConnection: 200 #Alaway same value with maxSimultaneousUsagePerConnection
    maxSimultaneousUsagePerConnection: 200 #Alaway same value with maxInProcessPerConnection
    minSimultaneousUsagePerConnection: 2 # to be increased if query returns a lot of data

thinkerpop:
  db:
    host: localhost
    port: 8182
