jnosql:
  tinkerpop:
    host: ws://localhost:8182
    user: neo4j
    password: admin123
  graph:
    provider: org.eclipse.jnosql.mapping.graph.connections.TinkerpopGraphConfiguration

traversals:
  filename: traversals.yml
spring:
  application:
    name: pocs
  datasource:
    driver-class-name: org.postgresql.Driver
    username: dev
    password: s3cr3t
    url: jdbc:postgresql://localhost:5432/dev_database
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        ddl-auto: update
      generate-ddl: true
server:
  port: 4000
  servlet:
    context-path: /pocs
aws:
  ssm:
    region: ca-central-1
  neptune:
    host: neptunedbinstance-zvdnrtvv7jvh.c9popfp3zboh.ca-central-1.neptune.amazonaws.com
    port: 8182
    username:
    password:
    enableSsl: false
    keystore:
    keystorePassword:
    maxConnectionPoolSize: 2
    maxInProcessPerConnection: 200 #Alaway same value with maxSimultaneousUsagePerConnection
    maxSimultaneousUsagePerConnection: 200 #Alaway same value with maxInProcessPerConnection
    minSimultaneousUsagePerConnection: 2 # to be increased if query returns a lot of data

thinkerpop:
  db:
    host: localhost
    port: 8182

logging:
  file:
    name: logs/app.log
  level:
    com:
      tiger:
        services: INFO
        handler: INFO
    org:
      springframework:
        web: DEBUG

file:
  pl17:
    xsd-path: /xsd
    xml-path: /generated