#___________________________________________________________________________
#1.Add brand param
post:
  tags:
    - param-endpoints
  summary: Register new param.
  operationId: addParam
  description: Add a brand new param
  parameters:
    - $ref: "../parameters/common.yml#/token"
  requestBody:
    content:
      application/json:
        schema:
          $ref: "../schemas/params.yml#/ParamRequest"
  responses:
    "201":
      description: Item created successfully.
      content:
        application/json:
          schema:
            $ref: "../schemas/params.yml#/ParamResponse"
    "400":
      $ref: "../responses/common.yml#/400APIError"
    "409":
      $ref: "../responses/common.yml#/409APIError"
    "500":
      $ref: "../responses/common.yml#/500APIError"

#___________________________________________________________________________
#4.Find page of param
get:
  tags:
    - param-endpoints
  summary: Fetch pages of params filtered by criteria.
  operationId: searchParams
  parameters:
    - $ref: "../parameters/common.yml#/token"
    - $ref: "../parameters/common.yml#/lastModifiedDate"
  responses:
    "200":
      description: Found item structure.
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "../schemas/params.yml#/ParamResponse"

    "400":
      $ref: "../responses/common.yml#/400APIError"
    "409":
      $ref: "../responses/common.yml#/409APIError"
    "500":
      $ref: "../responses/common.yml#/500APIError"
