openapi: 3.0.0
servers:
  - url: "http://localhost:4000"
    description: Server description

info:
  title: sample-management-rest
  version: 1.0.0
  description: Sample Management service
  contact:
    email: infos-dev@mendoz.labs
  license:
    name: SBT 1.0
    url: "https://www.licence.mendoz.labs"

tags:
  - name: sample-endpoints
    description: Samples management operations
  - name: graph-sample-endpoints
    description: Graph samples management operations
  - name: aws-params-endpoints
    description: AWS Parameter management operations

paths:
  /samples:
    $ref: "./paths/sample/get-post.yml"
  /samples/{id}:
    $ref: "./paths/sample/get-put-delete-patch.yml"

  /graph-samples:
    $ref: "./paths/graph/get-post.yml"
  /graph-samples/{id}:
    $ref: "./paths/graph/get-put-delete-patch.yml"

  /aws-parameters:
    $ref: "./paths/params/post.yml"
  /aws-parameters/{key}:
    $ref: "./paths/params/get-by-key.yml"
  /aws-parameters/path:
    $ref: "./paths/params/get-by-path.yml"

components:
  securitySchemes:
    implicit:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: "http://localhost/oauth/auth"
          scopes:
            write: allows modifying resources
            read: allows reading resources
  parameters:
    $ref: "./params/common.yml"
  schemas:
    $ref: "./schemas/params.yml"
  responses:
    $ref: "./responses/common.yml"
